# Generated by Django 5.1.2 on 2024-11-10 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('account_book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_accounts', to='dashboard.accountbook')),
            ],
        ),
    ]
